### ISSUE TITLE
[Feature Request] Ability to add * routes

### ISSUE THREAD

**Issue by ghost** [kajumito/gatsby-plugin-routes#3]
It would be very beneficial to be able to add a wild card, for example:

```
const path = require('path');
module.exports = [
  {
    path: '/masterplan/*',
    component: path.resolve(`src/pages/masterplan.js`)
  }
];
```

Which would work for all URL's and insert the component :)

**Comment by natezerk** [comment]
Actually, seems as though you can do this already!

**Comment by kajumito** [comment]
Thanks for the heads up! Haven't been using/testing wildcard feature.

**Comment by JoueBien** [comment]
Can you re-open this issues? the wild cards don't work in the latest build.

I'm trying with

`
{
    path: '/casestudy/*',
    component: path.resolve(`src/pages/test.tsx`)
  },

`

Which fails to resolve unless the route is exactly 
http://localhost:8000/casestudy/*

**Comment by ghost** [comment]
Yes, sorry this issue was never fixed. It would be hard to solve because the plugin works by creating individual html files for all the routes.

**Comment by pseelinger** [comment]
I was able to get this to work using template literals in my path:

``path: `/masterplan/*` ``

So url.com/masterplan/anything would be a valid URL. When built, it will sometimes route to the 404 page first, but it resolves itself fairly quickly. This was on v1.0.0
