### ISSUE TITLE
Conflict with pages created outside of plugin

### ISSUE THREAD

**Issue by ch2ch3** [kajumito/gatsby-plugin-routes#8]
Thanks for making this plugin!

I'm having an issue where I want to use this plugin and also programmatically create some other pages using [`createPages`](https://www.gatsbyjs.org/docs/node-apis/#createPages). However the line below is deleting those pages:

https://github.com/kajumito/gatsby-plugin-routes/blob/72e66b9084ee36eb74ee26da9a90c8c17cd6da99/src/gatsby-node.js#L47

It seems like a pretty heavy-handed restriction to delete pages that aren't defined in the routes file. What do you think about removing it?

**Comment by kajumito** [comment]
Hello @ch2ch3!

I updated plugin modules and fixed this issue.  [[v1.0.1](https://github.com/kajumito/gatsby-plugin-routes/releases/tag/v1.0.1)]

Thanks for reporting.

**Comment by kajumito** [comment]
Hello @ch2ch3!

I updated plugin modules and fixed this issue.  [[v1.0.1](https://github.com/kajumito/gatsby-plugin-routes/releases/tag/v1.0.1)]

Thanks for reporting.
